version: 2
jobs:
  build:
    working_directory: /workdir
    docker:
      - image: docker:git
        environment:
          IMAGE_NAME: fitzroy:rstudio
          DOCKER_PROJECT: thetinytechco

    steps:
      - checkout
      - run:
          name: Docker info
          command: |
            docker version
            docker info
      - restore_cache:
          keys:
            - cache-{{ .Branch }}
          paths:
            - /cache/layers.tar
      - run:
          name: Build docker image
          command: |
            docker build -t thetinytechco/fitzroy:rstudio -f rstudio/Dockerfile . 
      - run:
          name: Push Docker Image
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            docker push thetinytechco/fitzroy:rstudio