version: 2
jobs:
  build:
    working_directory: /workdir
    docker:
      - image: docker:git
        environment:
          IMAGE_NAME: fitzroy:rstudio
          DOCKER_PROJECT: thetinytechco
          RSTUDIO_VERSION: 3.4.1

    steps:
      - checkout
      - setup_remote_docker:
          version: 18.05.0-ce
      - run:
          name: Docker info
          command: |
            docker version
            docker info 
      - restore_cache:
          keys:
            - cache-{{ .Branch }}
          paths:
            - /cache/layers.tar
      - run:
          name: Build docker image
          command: |
            docker build -t thetinytechco/fitzroy:rstudio-${RSTUDIO_VERSION} -f rstudio/Dockerfile . 
            docker tag thetinytechco/fitzroy:rstudio-${RSTUDIO_VERSION} thetinytechco/fitzroy:latest
            docker tag thetinytechco/fitzroy:rstudio-${RSTUDIO_VERSION} thetinytechco/fitzroy:rstudio
      - run:
          name: Push Docker Image
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            docker push thetinytechco/fitzroy:latest
            docker push thetinytechco/fitzroy:rstudio
            docker push thetinytechco/fitzroy:rstudio-${RSTUDIO_VERSION}
            docker logout